# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('time', models.TimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chs.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('object', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='chs.Object')),
                ('event_name', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('object', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='chs.Object')),
                ('moves', models.BinaryField()),
                ('start_date', models.DateField(null=True)),
                ('location', models.CharField(max_length=60, null=True)),
                ('result', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('object', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='chs.Object')),
                ('moves', models.BinaryField()),
                ('opening_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('object', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='chs.Object')),
                ('firstname', models.CharField(blank=True, max_length=30)),
                ('lastname', models.CharField(blank=True, max_length=30)),
                ('elo_rating', models.IntegerField(null=True)),
                ('nationality', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chs.Account'),
        ),
        migrations.AddField(
            model_name='comment',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chs.Object'),
        ),
        migrations.AddField(
            model_name='account',
            name='can_edit',
            field=models.ManyToManyField(to='chs.Object'),
        ),
        migrations.AddField(
            model_name='game',
            name='black',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plays_black', to='chs.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chs.Event'),
        ),
        migrations.AddField(
            model_name='game',
            name='white',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plays_white', to='chs.Player'),
        ),
    ]
