from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',
        views.mainpage,
        name='mainpage'),
    url(r'^game/(?P<pk>[0-9]+)/$',
        views.GameDetail.as_view(),
        name='game'),
    url(r'^game/$',
        views.GameList.as_view(),
        name='game_list'),
    url(r'^game/search/$', views.search_game, name='game_search'),
    url(r'^game/create/$', views.create_game, name='game_create'),
    url(r'^game/add/$', views.add_game, name='game_add'),
    url(r'^game/add/pgn/$', views.add_game_pgn, name='game_add_pgn'),
    url(r'^player/(?P<pk>[0-9]+)/$',
        views.PlayerDetail.as_view(),
        name='player'),
    url(r'^player/$',
        views.PlayerList.as_view(),
        name='player_list'),
    url(r'^player/search/$', views.search_player, name='player_search'),
    url(r'^event/(?P<pk>[0-9]+)/$',
        views.EventDetail.as_view(),
        name='event'),
    url(r'^event/$',
        views.EventList.as_view(),
        name='event_list'),
    url(r'^event/search/$', views.search_event, name='event_search'),
    url(r'^opening/(?P<pk>[0-9]+)/$',
        views.OpeningDetail.as_view(),
        name='opening'),
    url(r'^opening/$',
        views.OpeningList.as_view(),
        name='opening_list'),
    url(r'^opening/search/$', views.search_opening, name='opening_search'),
    url(r'^opening/create/$', views.create_opening, name='opening_create'),
    url(r'^opening/add/$', views.add_opening, name='opening_add'),
    url(r'^(?P<pk>[0-9]+)/$',
        views.object,
        name='object'),
    url(r'^comment/(?P<pk>[0-9]+)/$',
        views.comment,
        name="comment"),
    url(r'^login/$',
        views.login,
        name="login"),
    url(r'^login/handle/$',
        views.handle_login,
        name="handle_login"),
    url(r'^logout/$',
        views.logout,
        name="logout"),
    url(r'^register/$',
        views.register,
        name="register"),
    url(r'^register/handle/$',
        views.handle_register,
        name="handle_register"),
]
